id: KitchenHallOnTriggerTimer
alias: KitchenHallOnTriggerTimer
description: ''
trigger:
  - platform: state
    entity_id: light.kitchenhalllight
    to: 'on'
condition: []
action:
  - service: timer.start
    target:
      entity_id: timer.kitchenhall_light_on_countdown
    data:
      duration: '00:10:00'
mode: single
