id: KitchenHallOffAfterTimer
alias: KitchenHallOffAfterTimer
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchenhall_light_on_countdown
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.kitchenhalllight
mode: single