- id: '1626920784509'
  alias: IKEA -> Hue Toggle Power
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: b5baa12d1a26a8ad901d8df8d402b3ba
    entity_id: light.hue_lightstrip_2
    domain: light
  mode: single
- id: '1626920868327'
  alias: IKEA -> Hue Brightness Up
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  condition: []
  action:
  - device_id: b5baa12d1a26a8ad901d8df8d402b3ba
    domain: light
    entity_id: light.hue_lightstrip_2
    type: brightness_increase
  mode: single
- id: '1626920884707'
  alias: IKEA -> Hue Brightness Down
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  condition: []
  action:
  - device_id: b5baa12d1a26a8ad901d8df8d402b3ba
    domain: light
    entity_id: light.hue_lightstrip_2
    type: brightness_decrease
  mode: single
- id: '1628146216133'
  alias: 'Brian Office Aqara Magic Cube '
  description: ''
  use_blueprint:
    path: brent/zha-aqara-magic-cube-57-actions.yaml
    input:
      remote: b3ce2b1c1dc23e7ec88ae1c852649300
      cube_flip_1:
      - service: switch.turn_on
        target:
          entity_id: switch.brianofficeledbar
      cube_flip_4:
      - service: switch.turn_off
        target:
          entity_id: switch.brianofficeledbar
