- id: '1626920784509'
  alias: IKEA -> Hue Toggle Power
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: b5baa12d1a26a8ad901d8df8d402b3ba
    entity_id: light.hue_lightstrip_2
    domain: light
  mode: single
- id: '1626920868327'
  alias: IKEA -> Hue Brightness Up
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_up
  condition: []
  action:
  - device_id: b5baa12d1a26a8ad901d8df8d402b3ba
    domain: light
    entity_id: light.hue_lightstrip_2
    type: brightness_increase
  mode: single
- id: '1626920884707'
  alias: IKEA -> Hue Brightness Down
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: dim_down
  condition: []
  action:
  - device_id: b5baa12d1a26a8ad901d8df8d402b3ba
    domain: light
    entity_id: light.hue_lightstrip_2
    type: brightness_decrease
  mode: single
- id: '1628146216133'
  alias: 'Brian Office Aqara Magic Cube '
  description: ''
  use_blueprint:
    path: brent/zha-aqara-magic-cube-57-actions.yaml
    input:
      remote: b3ce2b1c1dc23e7ec88ae1c852649300
      cube_flip_1:
      - type: turn_on
        device_id: e2d5e8d43bdca56726a839ecdf20d5ac
        entity_id: light.sengled_01_2aea0203_level_light_color_on_off
        domain: light
        brightness_pct: 30
      - type: turn_on
        device_id: 4e17e97b1f978fb30965feb2ea46c2b5
        entity_id: switch.brianofficeledbar
        domain: switch
      cube_flip_4:
      - type: turn_off
        device_id: e2d5e8d43bdca56726a839ecdf20d5ac
        entity_id: light.sengled_01_2aea0203_level_light_color_on_off
        domain: light
      - type: turn_off
        device_id: 4e17e97b1f978fb30965feb2ea46c2b5
        entity_id: switch.brianofficeledbar
        domain: switch
      - type: turn_off
        device_id: b5baa12d1a26a8ad901d8df8d402b3ba
        entity_id: light.hue_lightstrip_2
        domain: light
      rotate_right:
      - device_id: e2d5e8d43bdca56726a839ecdf20d5ac
        domain: light
        entity_id: light.sengled_01_2aea0203_level_light_color_on_off
        type: brightness_increase
      rotate_left:
      - device_id: e2d5e8d43bdca56726a839ecdf20d5ac
        domain: light
        entity_id: light.sengled_01_2aea0203_level_light_color_on_off
        type: brightness_decrease
      flip_any: true
      cube_flip_5:
      - type: turn_on
        device_id: b5baa12d1a26a8ad901d8df8d402b3ba
        entity_id: light.hue_lightstrip_2
        domain: light
        brightness_pct: 100
      cube_flip_6:
      - type: turn_off
        device_id: b5baa12d1a26a8ad901d8df8d402b3ba
        entity_id: light.hue_lightstrip_2
        domain: light
- id: '1628185959282'
  alias: Left Button IKEA toggle power on Brian Office LED
  description: ''
  trigger:
  - device_id: 8c374a1a2dc294ec7b4467957a7df0d5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: left
  condition: []
  action:
  - type: toggle
    device_id: 4e17e97b1f978fb30965feb2ea46c2b5
    entity_id: switch.brianofficeledbar
    domain: switch
  mode: single
- id: '1628299869781'
  alias: Motion-activated Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.ewelink_ms01_02_ias_zone
      light_target:
        entity_id: light.sengled_01_2aea0203_level_light_color_on_off
      no_motion_wait: 60
- id: '1628306255069'
  alias: Pantry light off after 5 minutes
  description: ''
  trigger:
  - platform: state
    entity_id: light.pantrylight
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: timer.start
    data:
      duration: 00:01:00
    target:
      entity_id: timer.pantry_light_on_countdown
  mode: single
- id: '1628309017551'
  alias: Water Heater Pump On
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /30
  condition:
  - condition: time
    after: 05:00:00
    before: '23:00:00'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.waterheaterpumpswitch
  - service: timer.start
    data:
      duration: 00:05:00
    target:
      entity_id: timer.waterheater_pump_on_countdown
  mode: single
- id: '1628309364895'
  alias: Water Heater Pump Off After Timer
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.waterheater_pump_on_countdown
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.waterheaterpumpswitch
  mode: single
- id: '1628315524668'
  alias: LaundryRoom_Off_After_Timer
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.laundryroom_light_on_countdown
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.laundryroomlight
  mode: single
- id: '1628315551454'
  alias: LaundryRoom_On_Trigger_Timer
  description: ''
  trigger:
  - platform: state
    entity_id: light.laundryroomlight
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: timer.start
    data:
      duration: 00:01:00
    target:
      entity_id: timer.laundryroom_light_on_countdown
  - condition: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    state: 'on'
  - service: timer.pause
    target:
      entity_id: timer.laundryroom_light_on_countdown
  mode: single
- id: '1628315601275'
  alias: LaundryRoom_Timer_Cancel_When_Off
  description: ''
  trigger:
  - platform: state
    entity_id: light.laundryroomlight
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: timer.cancel
    target:
      entity_id: timer.laundryroom_light_on_countdown
  mode: single
- id: '1628315619820'
  alias: LaundryRoom_Timer_Pause_During_Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    to: 'on'
  condition:
  - condition: state
    entity_id: light.laundryroomlight
    state: 'on'
  action:
  - service: timer.pause
    target:
      entity_id: timer.laundryroom_light_on_countdown
  mode: single
- id: '1628315635919'
  alias: LaundryRoom_Timer_Start_After_Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    to: 'off'
    from: 'on'
  condition: []
  action:
  - condition: state
    entity_id: light.laundryroomlight
    state: 'on'
  - service: timer.start
    data:
      duration: 00:01:00
    target:
      entity_id: timer.laundryroom_light_on_countdown
  mode: single
