# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# HomeAssistant Core
homeassistant:
  name: Cerezo House HA
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  #packages: !include_dir_list ./ha_integrations

# HTTP
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.6.15
  ip_ban_enabled: true
  login_attempts_threshold: 5

mobile_app:
discovery:
python_script:

# Dashboard
# lovelace:
#  mode: yaml

# MQTT
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true

# Logger
logger:
  default: info
  logs:
    homeassistant.components.yamaha: critical
    custom_components.my_integration: critical

# InfluxDB
influxdb:
  ssl: false
  host: !secret influxhost
  port: 8086
  # username: !secret influxuser
  # password: !secret influxpass
  database: !secret influxdatabase
  max_retries: 9
  default_measurement: state

# Text to speech
tts:
  - platform: google_translate

# Device Tracking
device_tracker:
  - platform: ping
    interval_seconds: 30
    consider_home: 600
    hosts:
      bmccarty: 192.168.7.40
      amccarty: 192.168.7.41
      tesla3: 192.168.7.211
      lmccarty: 192.168.7.182
      mmccarty: 192.168.7.103

# Example configuration.yaml entry
nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_projectid
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriberid

# YAML Configuration Files
automation: !include automations.yaml
automation split: !include_dir_list ./ha_automations

group: !include groups.yaml
group split: !include_dir_list ./ha_groups

script: !include scripts.yaml

scene: !include scenes.yaml
scene split: !include_dir_list ./ha_scenes

sensor: !include sensor.yaml
sensor split: !include_dir_list ./ha_sensors

binary_sensor: !include_dir_list ./ha_binary_sensors

switch: !include switch.yaml
switch split: !include_dir_list ./ha_switches

cover: !include cover.yaml
cover split: !include_dir_list ./ha_covers

climate: !include climate.yaml
climate split: !include_dir_list ./ha_climates

# Shell commands
shell_command:
  pushtogit: bash /config/ha_gitpush.sh
