# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named ./ha_themes

# HomeAssistant Core
homeassistant:
  name: Cerezo House HA
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  #packages: !include_dir_list ./ha_integrations

# HTTP
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.6.15
  ip_ban_enabled: true
  login_attempts_threshold: 5

mobile_app:
discovery:
python_script:
sun:
recorder:
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.date_time_utc

fastdotcom:
  scan_interval: '00:05:01'

# Dashboard
# lovelace:
#  mode: yaml

# MQTT
mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true

# Logger
logger:
  default: info
  logs:
    homeassistant.components.yamaha: critical
    custom_components.my_integration: critical

# InfluxDB
influxdb:
  ssl: false
  host: !secret influxhost
  port: 8086
  # username: !secret influxuser
  # password: !secret influxpass
  database: !secret influxdatabase
  max_retries: 9
  default_measurement: state

# Text to speech
tts:
  - platform: google_translate

# Device Tracking
device_tracker:
  - platform: ping
    interval_seconds: 30
    consider_home: 600
    hosts:
      bmccarty: 192.168.6.228
      tesla3: 192.168.6.227

# Example configuration.yaml entry
nest:
  client_id: !secret nest_clientid
  client_secret: !secret nest_clientsecret
  # "Project ID" in the Device Access Console
  project_id: !secret nest_projectid
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret nest_subscriberid

# YAML Configuration Files
automation: !include automations.yaml
automation split: !include_dir_list ./ha_automations

group: !include groups.yaml
group split: !include_dir_list ./ha_groups

script: !include scripts.yaml

scene: !include scenes.yaml
scene split: !include_dir_list ./ha_scenes

sensor: !include sensor.yaml
sensor split: !include_dir_list ./ha_sensors

binary_sensor: !include_dir_list ./ha_binary_sensors

switch: !include switch.yaml
switch split: !include_dir_list ./ha_switches

cover: !include cover.yaml
cover split: !include_dir_list ./ha_covers

climate: !include climate.yaml
climate split: !include_dir_list ./ha_climates

timer:
  laundryroom_light_on_countdown:
    name: LaundryRoom Light On Countdown Timer
  pantry_light_on_countdown:
    name: Pantry Light On Countdown Timer
  amber_closet_light_on_countdown:
    name: Amber Closet Light On Countdown Timer
  patio_light_on_countdown:
    name: Patio Light On Countdown Timer
  kitchenhall_light_on_countdown:
    name: Kitchen Hall Light On Countdown Timer

# Shell commands
shell_command:
  pushtogit: bash /config/ha_shell/ha_gitpush.sh
