# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include_dir_merge_named ./ha_themes

# HomeAssistant Core
homeassistant:
  name: Cerezo House HA
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named ./ha_packages


mobile_app:
discovery:
python_script:
sun:
recorder:

# YAML Configuration Files
automation: !include automations.yaml
automation split: !include_dir_list ./ha_automations

group: !include groups.yaml
group split: !include_dir_list ./ha_groups

script: !include scripts.yaml
script split: !include_dir_list ./ha_scripts

scene: !include scenes.yaml
scene split: !include_dir_list ./ha_scenes

sensor: !include sensor.yaml
sensor split: !include_dir_merge_list ./ha_sensors

binary_sensor: !include_dir_list ./ha_binary_sensors

switch: !include switch.yaml
switch split: !include_dir_merge_list ./ha_switches

cover: !include cover.yaml
cover split: !include_dir_list ./ha_covers

climate: !include climate.yaml
climate split: !include_dir_merge_list ./ha_climates
