title: My Awesome Home
resources:
  - url: /local/dual-gauge-card.js
    type: js
views:
  - title: Home
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: light.porchdimmer
      - type: button
        tap_action:
          action: toggle
        entity: switch.outsidelights
      - type: button
        tap_action:
          action: toggle
        entity: light.foyerdimmer
      - type: gauge
        entity: sensor.speedtest_download
        min: 0
        max: 1000
  - title: Climate
    path: climate
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.upstairs_temperature
          - entity: sensor.main_floor_temperature
          - entity: sensor.aidan_bedroom_temperature
          - entity: sensor.liam_bedroom_temperature
          - entity: sensor.living_room_temperature
          - entity: sensor.sophia_bedroom_temperature
          - entity: sensor.amber_office_temperature_esphome
          - entity: sensor.dad_room_temperature_esphome
          - entity: sensor.attic2_ds18b20_temperature
          - entity: sensor.atticnodemcu_bme280_temperature
          - entity: sensor.garagesidedoorsensor_bme280_temperature
        title: Temperature
      - type: entities
        entities:
          - entity: sensor.aidan_room_humidity_esphome
          - entity: sensor.amber_office_humidity_esphome
          - entity: sensor.atticnodemcu_bme280_humidity
          - entity: sensor.dad_room_humidity_esphome
          - entity: sensor.garagesidedoorsensor_bme280_humidity
          - entity: sensor.loft_humidity_esphome
          - entity: sensor.main_floor_humidity
          - entity: sensor.5_humidity_esphome
          - entity: sensor.upstairs_humidity
          - entity: sensor.garagesidedoorsensor_bme280_humidity
        title: Humidity
      - type: thermostat
        entity: climate.main_floor
      - type: thermostat
        entity: climate.upstairs
      - type: custom:dual-gauge-card
        title: Living room
        min: -20
        max: 40
        outer:
          entity: climate.main_floor
          attribute: current_temperature
          label: "Current"
          unit: "°C"
        inner:
          entity: climate.main_floor
          label: "Target"
          attribute: temperature
          unit: "°C"
        colors:
          - color: "var(--label-badge-red)"
            value: 27.5
          - color: "var(--label-badge-green)"
            value: 25
          - color: "var(--label-badge-yellow)"
            value: 18
          - color: "var(--label-badge-blue)"
            value: 0
          - color: "var(--paper-blue-400)"
            value: -40
  - title: Master
    path: master
    badges: []
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: switch.masterlightceiling
        show_icon: true
        icon: mdi:lightbulb
      - type: button
        tap_action:
          action: toggle
        entity: switch.masterlightoutlet
        show_icon: true
        icon: mdi:lightbulb
  - title: Garage
    path: garage
    badges: []
    cards:
      - type: button
        tap_action:
          action: toggle
        entity: switch.garagelight
        icon: mdi:lightbulb
        name: Garage Overhead Light
      - type: button
        tap_action:
          action: toggle
        entity: switch.garagebenchlight
        icon: mdi:lightbulb
        name: Garage Bench Light
      - type: button
        tap_action:
          action: toggle
        entity: switch.garagepowertoollight
        icon: mdi:lightbulb
        name: Garage PowerTool Light
      - type: button
        tap_action:
          action: toggle
        entity: cover.garage_door
      - type: gauge
        min: 0
        max: 130
        entity: sensor.garagesidedoorsensor_bme280_temperature
  - title: Pool
    path: pool
    badges: []
    cards:
      - type: entities
        entities:
          - entity: switch.filter_pump
          - entity: switch.waterfall
          - entity: switch.spa_jets
          - entity: sensor.pool_temp
          - entity: sensor.spa_temp
