- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: moon

- platform: worldclock
  time_zone: America/Los_Angeles

- platform: sun2
  monitored_conditions:
    - solar_midnight
    - astronomical_dawn
    - nautical_dawn
    - dawn
    - sunrise
    - solar_noon
    - sunset
    - dusk
    - nautical_dusk
    - astronomical_dusk
    - daylight
    - civil_daylight
    - nautical_daylight
    - astronomical_daylight
    - night
    - civil_night
    - nautical_night
    - astronomical_night
    - elevation
    - min_elevation
    - max_elevation

- platform: sun2
  entity_namespace: LA
  latitude: 34.3769732
  longitude: -118.5435177
  time_zone: America/Los_Angeles
  elevation: 398
  monitored_conditions:
    - sunrise
    - sunset

- platform: template
  sensors:
    today_is:
      friendly_name: 'Today is'
      value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
    month_is:
      friendly_name: 'Month is'
      value_template: "{{ ['January','February','March','April','May','June','July','August','September','October','November','December'][now().month-1] }}"