- platform: integration
  source: sensor.mainsconsumption
  name: iotawatt_total_sce_kwh
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.solarproduction
  name: iotawatt_total_solar_kwh
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.mainsexport
  name: iotawatt_exporttogrid_kwh
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.mainsexport
  name: iotawatt_gridexport
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.simexport
  name: iotawatt_simexport
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.telsa_combined
  name: tesla_combined_kwh
  unit_prefix: k
  round: 2