- platform: integration
  source: sensor.mainsconsumption
  name: iotawatt_total_sce_kwh
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.solarproduction
  name: iotawatt_total_solar_kwh
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.mainsexport
  name: iotawatt_export_to_grid_kwh
  unit_prefix: k
  round: 2
