- platform: integration
  source: sensor.solar_combined_power
  name: solar_energy
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.total_monitored_dev
  name: total_monitored_kwh
  unit_prefix: k
  round: 2