- platform: template
  sensors:
    house_status:
      value_template: >-
        {% if (is_state("person.brian_mccarty", "home")) 
        or (is_state("person.amber_mccarty", "home"))  
        or (is_state("person.liam_mccarty", "home"))  
        or (is_state("person.aidan_mccarty", "home"))  
        or (is_state("person.sophia_mccarty", "home")) -%}
        Occupied
        {%- else -%}
        Unoccupied
        {%- endif %}