- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"

- platform: command_line
  command: wc -l /config/configuration.yaml | awk '{ print $1 }'
  name: Config File Size

- platform: statistics
  name: 'Unraid Energy Current Stats'
  entity_id: sensor.unraidswitch_energy_current
  sampling_size: 4
  max_age:
    hours: 24

- platform: statistics
  name: 'Unraid Energy Power Stats'
  entity_id: sensor.unraidswitch_energy_power
  sampling_size: 4
  max_age:
    hours: 24

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: memory_use_percent
    - type: last_boot
