- platform: mqtt
  unique_id: publicIPv4
  state_topic: "stats/publicIPv4"
  name: "publicIPv4"
  value_template: "{{ value }}"    
  icon: mdi:cloud

- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"

- platform: command_line
  command: wc -l /config/configuration.yaml | awk '{ print $1 }'
  name: Config File Size

- platform: statistics
  name: 'Unraid Energy Current Stats'
  entity_id: sensor.unraidswitch_energy_current
  sampling_size: 4
  max_age:
    hours: 24

- platform: statistics
  name: 'Unraid Energy Power Stats'
  entity_id: sensor.unraidswitch_energy_power
  sampling_size: 4
  max_age:
    hours: 24

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: memory_use_percent
    - type: last_boot

#Untangle
- platform: scrape
  name: firewall_available_version
  resource: https://wiki.untangle.com/index.php/Date_Changelog
  select: ".toctext"
  scan_interval: 3600
  value_template: "{{ value.split(' ')[0] }}"
  verify_ssl: true

- platform: snmp
  name: 'Firewall CPU 5min'
  host: !secret firewall_ip
  baseoid: 1.3.6.1.4.1.2021.10.1.3.2
  community: !secret firewall_snmp_community
  version: '2c'
  value_template: '{{ value | float }}'
  unit_of_measurement: '%'
  scan_interval: 60

- platform: snmp
  name: 'Firewall WAN In'
  host: !secret firewall_ip
  baseoid: 1.3.6.1.2.1.31.1.1.1.6.3
  community: !secret firewall_snmp_community
  version: '2c'
  scan_interval: 60

- platform: snmp
  name: 'Firewall WAN Out'
  host: !secret firewall_ip
  baseoid: 1.3.6.1.2.1.31.1.1.1.10.3
  community: !secret firewall_snmp_community
  version: '2c'
  scan_interval: 60

- platform: template
  sensors:
    firewall_internet_in_mbps:
      value_template: "{{ (state_attr('sensor.firewall_wan_in_stats','change_rate')|float*8*(state_attr('sensor.firewall_wan_in_stats', 'sampling_size')-1)/1000000)|round(2) }}"
      unit_of_measurement: 'MBps'
  #    entity_id: sensor.firewall_wan_in_stats
    firewall_internet_out_mbps:
      value_template: "{{ (state_attr('sensor.firewall_wan_out_stats','change_rate')|float*8*(state_attr('sensor.firewall_wan_out_stats', 'sampling_size')-1)/1000000)|round(2) }}"
      unit_of_measurement: 'MBps'
    #   entity_id: sensor.firewall_wan_out_stats

- platform: snmp
  name: 'Firewall Memory Used GB'
  host: !secret firewall_ip
  baseoid: 1.3.6.1.4.1.2021.4.6.0
  community: !secret firewall_snmp_community
  version: '2c'
  value_template: '{{ (value | float /1024 /1024) | round(1) }}'
  unit_of_measurement: 'GB'
  scan_interval: 60

- platform: statistics
  name: 'Firewall WAN In Stats'
  entity_id: sensor.firewall_wan_in
  sampling_size: 4
  max_age:
    hours: 24

- platform: statistics
  name: 'Firewall WAN Out Stats'
  entity_id: sensor.firewall_wan_out
  sampling_size: 4
  max_age:
    hours: 24

- platform: snmp
  name: 'Firewall Uptime'
  host: !secret firewall_ip
  baseoid: 1.3.6.1.2.1.25.1.1.0
  community: !secret firewall_snmp_community
  version: '2c'
  scan_interval: 60
  value_template: >-
    {% set time = (value | int) | int %}
    {% set minutes = ((time % 360000) / 6000) | int%}
    {% set hours = ((time % 8640000) / 360000) | int %}
    {% set days = (time / 8640000) | int %}
      {%  if time < 60 -%}
        Less then 1 min
        {%  else -%}
        {%  if days > 0 -%}
          {{ days }}d
        {%  endif -%}
        {%  if hours > 0 -%}
          {%  if days > 0 -%}
            {{ ' ' }}
          {%  endif -%}
          {{ hours }}hr
        {%  endif -%}
        {%  if minutes > 0 -%}
          {%  if days > 0 or hours > 0 -%}
            {{ ' ' }}
          {%  endif -%}
          {{ minutes }}min
        {%  endif -%}
      {%  endif -%}