id: PatioOnTriggerTimer
alias: PatioOnTriggerTimer
description: ''
trigger:
  - platform: state
    entity_id: light.patiolight1
    to: 'on'
condition: []
action:
  - service: timer.start
    target:
      entity_id: timer.patio_light_on_countdown
    data:
      duration: '00:30:00'
mode: single
