id: door_garage_side_open
alias: Door - Garage Side Door Open - Turn on lights
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.garage_side_door_status
    to: "on"
condition: []
action:
  - scene: scene.garage_lights_on
mode: single
