id: light_patio_porch_off_1am
alias: Lights - Porch and Patio Off at 1am
description: ''
trigger:
- platform: time
  at: 01:00:00
condition: []
action:
- type: turn_off
  device_id: 4d9f62f15c7ede3f4991fc61526281c5
  entity_id: light.switch_porch
  domain: light
- type: turn_off
  device_id: cb79b32771533dad0137e75af7daa5f2
  entity_id: switch.switch_outside
  domain: switch
mode: single