id: Amber_Office_Lights_On
alias: Amber Office Lights On
description: ''
trigger:
- platform: device
  type: turned_on
  device_id: 6bb5fd190203838a17e11ea696ec47e5
  entity_id: light.amber_office_overhead_level
  domain: light
condition: []
action:
- service: light.turn_on
  data:
    entity_id: light.amber_office_bloom
    color_name: gold
    brightness: 255
  entity_id: light.amber_office_bloom
mode: single