id: AmberClosetOffAfterTimer
alias: AmberClosetOffAfterTimer
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.amber_closet_light_on_countdown
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.amberclosetlight
mode: single