id: ffaea2f3-f2ba-4f4b-b78f-aff831b64db5
alias: LaundryRoom_Off_After_Timer
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.laundryroom_light_on_countdown
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.laundryroomlight
mode: single