id: 89d944d6-5ddf-4a4a-b44a-ef96fbbc743d
alias: LaundryRoom_On_Trigger_Motion_On_Timer
description: ''
trigger:
  - platform: state
    entity_id: light.laundryroomlight
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    state: 'on'
action:
  - service: timer.start
    data:
      duration: '00:01:00'
    target:
      entity_id: timer.laundryroom_light_on_countdown
  - service: timer.pause
    target:
      entity_id: timer.laundryroom_light_on_countdown
mode: single
