id: 018aac65-c76d-46e2-8a5b-425c87aefd8f
alias: LaundryRoom_Timer_Start_After_Motion
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    to: 'off'
condition: []
action:
  - service: timer.start
    data:
      duration: '00:01:00'
    target:
      entity_id: timer.laundryroom_light_on_countdown
mode: single
