id: 87071bb8-37cf-4f72-9787-196fc42467f2
alias: LaundryRoom_Timer_Cancel_When_Off
description: ''
trigger:
  - platform: state
    entity_id: light.laundryroomlight
    to: 'off'
condition: []
action:
  - service: timer.cancel
    target:
      entity_id: timer.laundryroom_light_on_countdown
mode: single
