id: 8ec19c97-4d21-4e57-a233-9939f0cd22b6
alias: LaundryRoom_On_Trigger_Motion_Off_Timer
description: ''
trigger:
  - platform: state
    entity_id: light.laundryroomlight
    to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    state: 'off'
action:
  - service: timer.start
    target:
      entity_id: timer.laundryroom_light_on_countdown
    data:
      duration: '00:01:00'
mode: single
