id: 781f6a05-5618-4cd9-b8e9-813100951078
alias: LaundryRoom_Timer_Pause_During_Motion
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.laundryroommotion_a7254423_ias_zone
    to: 'on'
condition:
  - condition: state
    entity_id: light.laundryroomlight
    state: 'on'
action:
  - service: timer.pause
    target:
      entity_id: timer.laundryroom_light_on_countdown
mode: single
