id: 16659a07-d6b8-4bb9-8bb2-e73a398f2810
alias: Lights - Garage light off after 1 hour
description: ''
trigger:
- platform: state
  entity_id: switch.sonoff_c82b96dbafe7
  to: 'on'
  for: 01:00:00
condition: []
action:
- service: switch.turn_off
  data: {}
  entity_id: switch.sonoff_c82b96dbafe7
- service: switch.turn_off
  data: {}
  entity_id: switch.garage_overworkbench
mode: single