id: 9d852d35-7ba0-4c28-b434-7af8b34be602
alias: Pantry_Timer_Start_After_Motion
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.pantrymotion_ias_zone
    to: 'off'
condition: []
action:
  - service: timer.start
    data:
      duration: '00:01:00'
    target:
      entity_id: timer.pantry_light_on_countdown
mode: single
