id: e080588e-53c9-4e60-913f-7bf9684dd329
alias: Pantry_Off_After_Timer
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.pantry_light_on_countdown
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.pantrylight
mode: single