id: 1736db3f-4b60-4411-83b3-b580d217b4bc
alias: PantryCancelTimerWhenOff
description: ''
trigger:
  - platform: state
    entity_id: light.pantrylight
    to: 'off'
condition: []
action:
  - service: timer.cancel
    target:
      entity_id: timer.pantry_light_on_countdown
mode: single
