id: 3423bb22-55b2-46e0-b5c7-aa5a74ce7d08
alias: Patio2OnTriggerTimer
description: ''
trigger:
  - platform: state
    entity_id: light.patiolight2
    to: 'on'
condition: []
action:
  - service: timer.start
    target:
      entity_id: timer.patio2_light_on_countdown
    data:
      duration: '00:30:00'
mode: single
