id: bef9e2a4-35a7-4533-b22b-9963d3e6855a
alias: Patio2OffAfterTimer
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.patio2_light_on_countdown
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.patiolight2
mode: single