id: PantryOffAfterTimer
alias: PantryOffAfterTimer
description: ''
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.pantry_light_on_countdown
condition: []
action:
  - service: light.turn_off
    target:
      entity_id: light.pantrylight
mode: single