id: 34197312-d4b4-4861-a1b7-ef53386e9fd3
alias: 'System: shellies announce'
trigger:
- platform: homeassistant
  event: start
- platform: time_pattern
  hours: /1
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce