id: shellies_announce
alias: Shellies Announce
trigger:
- platform: homeassistant
  event: start
- platform: time_pattern
  hours: /1
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce