substitutions:
  esphome_name: esptempsensor02
esphome:
  name: ${esphome_name}
  platform: ESP32
  board: mhetesp32devkit
wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_pass
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.7.54
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.7.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
logger:
  level: debug
#mqtt:
#  broker: 192.168.7.12
#  username: !secret esphome_mqtt_user
#  password: !secret esphome_mqtt_pass
api:
  reboot_timeout: 60min
  password: !secret esphome_api_pass
ota:
  password: !secret esphome_ota_pass
time:
#  - platform: homeassistant
  
esp32_ble_tracker:
switch:
  - platform: gpio
    name: "${esphome_name}-Onboard-LED"
    pin: 2
    inverted: True
  - platform: restart
    name: ${esphome_name}-restart
    id: restart_switch
sensor:
  - platform: uptime
    name: "${esphome_name}_Uptime Sensor"
    
  - platform: wifi_signal
    name: "${esphome_name} WiFi Signal"
    update_interval: 60s
    
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:29:05:39
    bindkey: "34840444fdd37168f8cbfffe7e0169f8"
    temperature:
      name: "ESP Kitchen Temperature"
    humidity:
      name: "ESP Kitchen Humidity"
    battery_level:
      name: "ESP Kitchen Battery Level"

  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:E8:06:47
    bindkey: "5509fb117751e9667ac0b3c894b92c12"
    temperature:
      name: "ESP Sensor7 Temperature"
    humidity:
      name: "ESP Sensor7 Humidity"
    battery_level:
      name: "ESP Sensor7 Battery Level"
  
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:2C:71:C6
    bindkey: "a926ebc4b584828076c7253cdb70e5eb"
    temperature:
      name: "ESP Sensor8 Temperature"
    humidity:
      name: "ESP Sensor8 Humidity"
    battery_level:
      name: "ESP Sensor8 Battery Level"
  
  - platform: xiaomi_lywsd03mmc
    mac_address: A4:C1:38:3C:4C:0D
    bindkey: "327bbb5818a849e4a7e108e2ad3effb1"
    temperature:
      name: "ESP Sensor9 Temperature"
    humidity:
      name: "ESP Sensor9 Humidity"
    battery_level:
      name: "ESP Sensor9 Battery Level"